schema_version = 1
description = "Premium users in the European operating region"
type = "bool"

[resolve]
default = false

[[resolve.rule]]
when = '(variables["premium_users"]) && (variables["eu_users"])'
value = true
