schema_version = 1

description = "Queue used for manual fraud review"
type = "string"

[resolve]
default = "risk-standard"

[[resolve.rule]]
when = 'env.qualifier["high-value-cart"]'
value = "risk-priority"

[[resolve.rule]]
when = 'env.qualifier["eu-users"]'
value = "risk-eu"
