schema_version = 1

description = "Whether the user should receive admin UI affordances"
type = "bool"

[values]
off = false
on = true

[resolve]
default = "off"

[[resolve.rule]]
qualifier = "admin-users"
value = "on"
